name: rest_resource
description: REST-resource creation base
version: 0.0.1
homepage: https://github.com/alexd1971/rest_resource
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.11.3+17
  quiver: ^2.0.0
  
dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  